### ISSUE TITLE
HTTPError: 400 Client Error: Bad Request for url: https://api.cloudflare.com/client/v4/zones

### ISSUE THREAD

**Issue by dennison-williams-stjames** [SeattleDevs/letsencrypt-cloudflare-hook#6]
I am reopening this issue [from the forked version ](https://github.com/kappataumu/letsencrypt-cloudflare-hook/issues/57)because I am still experiencing it.

I also tried [the fix in this comment](https://github.com/kappataumu/letsencrypt-cloudflare-hook/issues/57#issuecomment-554657293) which did not resolve the issue.

````(env) ~/bin/letsencrypt/dehydrated# ./dehydrated --challenge dns-01 -k hooks/cloudflare/hook.py -c -d subdomain.stjamesinfirmary.org
#
# !! WARNING !! No main config file found, using default config!
#
 + CloudFlare hook executing: startup_hook
 + Creating chain cache directory ~/bin/letsencrypt/dehydrated/chains
Processing openemr.stjamesinfirmary.org
 + Creating new directory ~/bin/letsencrypt/dehydrated/certs/subdomain.stjamesinfirmary.org ...
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for subdomain.stjamesinfirmary.org
 + 1 pending challenge(s)
 + Deploying challenge tokens...
 + CloudFlare hook executing: deploy_challenge
 + Creating TXT record: openemr.stjamesinfirmary.org => NZTybLCOjWp-QhekMq11Zx088BqwLbSC0nE6mLjXqBw
 + Challenge: o-Hus6X9iF_4f2J79kpGd7zGePyOerKi_GAhnxu8i6s
Traceback (most recent call last):
  File "hooks/cloudflare/hook.py", line 206, in <module>
    main(sys.argv[1:])
  File "hooks/cloudflare/hook.py", line 203, in main
    ops[argv[0]](argv[1:])
  File "hooks/cloudflare/hook.py", line 167, in create_all_txt_records
    create_txt_record(args[i:i+X])
  File "hooks/cloudflare/hook.py", line 105, in create_txt_record
    zone_id = _get_zone_id(domain)
  File "hooks/cloudflare/hook.py", line 82, in _get_zone_id
    r.raise_for_status()
  File "/root/systems/medicaldb.sji.l/root/bin/letsencrypt/env/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.cloudflare.com/client/v4/zones?name=stjamesinfirmary.org
ERROR: deploy_challenge hook returned with non-zero exit code
 + CloudFlare hook executing: exit_hook
````

**Comment by YasharF** [comment]
I have updated the current version in this depo with the latest dependencies and ran it a few minutes ago.  It is running without issues on Python 3.

Line 82 might be erroring out because of an out of date version of the tld package (fixed in this repo).

My environment is using Python 3.8.5.  Can you make sure you are fully updated with os, python, and pip package patches and see if you are still having issues with the version in this repo?

Thanks

**Comment by gruentee** [comment]
Hi Yashar!

First of all – happy (late) 2021 and thanks for taking over the project!

Unfortunately I'm experiencing the same issue, even after changing `tld` to version `0.12.4`.

My software versions:

```shell
$ python --version
Python 3.8.5
$  $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
$ uname -a
$ uname -a
Linux hc2 5.4.83-odroidxu4 #20.11.3 SMP PREEMPT Fri Dec 11 21:34:15 CET 2020 armv7l armv7l armv7l GNU/Linux
$ pip3 list | grep tld
tld                        0.12.4
```

Hope that helps.

**Comment by YasharF** [comment]
I just ran the current code in the repo and it went through.  My guess is that you might be having a configuration issue.  I did the refresh using the following script.  Make sure to fill out the proper data for the three export fields that I have marked as `FILL_ME` :  CF_EMAIL, CF_KEY, HMAILSERVER_DOMAIN

```
#!/bin/bash

export CF_EMAIL='FILL_ME'
export CF_KEY='FILL_ME'
export DOMAIN='FILL_ME'
export CF_DNS_SERVERS='8.8.8.8 8.8.4.4'
# export CF_DEBUG='true'

dehydrated/dehydrated -c -d $DOMAIN -t dns-01 -k 'dehydrated/hooks/cloudflare/hook.py'

cp dehydrated/certs/$DOMAIN/privkey.pem $DOMAIN.letsencrypt.key
cp dehydrated/certs/$DOMAIN/fullchain.pem $DOMAIN.letsencrypt.crt

exit 0

```

**Comment by svennd** [comment]
Just for reference, I faced a similar issue, with a token.This requires a different authentication request; instead
```   
CF_HEADERS = [{
        'X-Auth-Email': e,
        'X-Auth-Key'  : k,
```

You would need 
```    
CF_HEADERS = [{
        'Authorization': 'Bearer ' + k,
        #'X-Auth-Email': e,
        #'X-Auth-Key'  : k,
```  

Of course this would then only work with tokens. (and not with the Global API Key)
